### ISSUE TITLE
python string literals (not docstrings)

### ISSUE THREAD

**Issue by indigoviolet** [QBobWatson/poporg#11]
Thank you for this great library!

(In a python-mode buffer with poporg-mode enabled) I find that poporg works as expected for docstrings, but not for string literals. This would be useful for the case of SQL statements in Python string literals. Do you have any suggestions on how I can make this work? If not please consider this a feature request.

**Comment by QBobWatson** [comment]
Poporg will edit a string if it is preceded only by whitespace on its line.  Try this:
```python
query = \
    'DELETE * FROM my_table'
```

**Comment by indigoviolet** [comment]
Thanks for the quick response! That does work. Is that a hard requirement or can I customize it somehow?

**Comment by QBobWatson** [comment]
The code uses the whitespace before the string/comment to determine the common prefix when re-inserting into the buffer -- otherwise it doesn't know how much you want the string indented when you add new lines.  This could be a configurable; pull requests are welcome!
