### ISSUE TITLE
Using C-c ' as key binding?

### ISSUE THREAD

**Issue by ibizaman** [QBobWatson/poporg#6]
I'm trying this as a keybinding to match the keybinding to edit org src-blocks. Looks like it works fine for now. In an org buffer, when in a src-block, using `C-c '` edits using `org-edit-special` while elsewhere it uses `poporg-dwin`.

Was there a particular reason to propose using `C-c "` instead of `C-c '`?

**Comment by QBobWatson** [comment]
I think I chose `C-c "` because I was doing a lot of coding in python at the time, where the documentation tends to be enclosed in triple double-quotes.  But you can set it to whatever you want -- there's no default in the package.
